name: finara_app_v1
description: "Finara App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  provider: ^6.1.2

  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.4

  url_launcher: ^6.2.5
  intl: ^0.18.1

  youtube_player_iframe: ^5.0.0
  flutter_inappwebview: ^6.0.0

  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  # LA LIBRERÍA DE ANIMACIÓN VA AQUÍ:
  animated_text_kit: ^4.2.2
  
  # --- LIBRERÍAS DE TRADUCCIÓN (GOOGLE ML KIT) ---
  google_mlkit_translation: ^0.12.0
  google_mlkit_language_id: ^0.10.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  flutter_inappwebview: ^6.0.0
#
#
#
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo_finara.png"